# Generated by Django 2.1.5 on 2019-01-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190114_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='O boy é STAFF?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userame',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nome do usuário'),
        ),
    ]
